local f = io.open('RADPRIME.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 RADPRIME.sh')
os.execute('killall -9 tg')
os.execute('rm -rf RADPRIME.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('RADPRIME.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 RAD PRIME.sh')
os.execute('screen ./RADPRIME.sh')
